### ISSUE TITLE
Ошибки при использовании groupLongPollEvents

### ISSUE THREAD

**Issue by LionZXY** [Anton3/kotlin-vk-api#2]
При попытке использовать LongPolling API вот такое приходит:
```
GlobalScope.launch {
            val api = clientFactory.group(groupToken)
            val groupChannel = groupLongPollEvents(api, Integer.valueOf(Credentials.get(CredentialsEnum.VK_IU4_ID)), 10000)
            groupChannel.consumeEach {
                println(it)
            }
        }
```

Сама ошибка:
```
[WARN ] Network troubles
NotImplemented(id=188203694, attach={state=typing, from_id=76844299, to_id=-188203694})
[WARN ] LongPoll error
com.fasterxml.jackson.module.kotlin.MissingKotlinParameterException: Instantiation of [simple type, class name.anton3.vkapi.generated.messages.objects.Message] value failed for JSON property date due to missing (therefore NULL) value for creator parameter date which is a non-nullable type
 at [Source: (String)"{"ts":"20","updates":[{"type":"message_new","object":{"message":{"date":1572599291,"from_id":76844299,"id":11,"out":0,"peer_id":76844299,"text":"Превед","conversation_message_id":11,"fwd_messages":[],"important":false,"random_id":0,"attachments":[],"is_hidden":false},"client_info":{"button_actions":["text"],"lang_id":3}},"group_id":188203694}]}
"; line: 1, column: 322] (through reference chain: name.anton3.vkapi.methods.longpoll.LongPollResponse["updates"]->java.util.ArrayList[0]->name.anton3.vkapi.methods.callback.MessageNew["object"]->name.anton3.vkapi.generated.messages.objects.Message["date"])
	at com.fasterxml.jackson.module.kotlin.KotlinValueInstantiator.createFromObjectWith(KotlinValueInstantiator.kt:107) ~[jackson-module-kotlin-2.10.0.jar:2.10.0]
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:198) ~[jackson-databind-2.10.0.jar:2.10.0]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:488) ~[jackson-databind-2.10.0.jar:2.10.0]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287) ~[jackson-databind-2.10.0.jar:2.10.0]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326) ~[jackson-databind-2.10.0.jar:2.10.0]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159) ~[jackson-databind-2.10.0.jar:2.10.0]
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530) ~[jackson-databind-2.10.0.jar:2.10.0]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528) ~[jackson-databind-2.10.0.jar:2.10.0]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417) ~[jackson-databind-2.10.0.jar:2.10.0]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287) ~[jackson-databind-2.10.0.jar:2.10.0]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326) ~[jackson-databind-2.10.0.jar:2.10.0]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:194) ~[jackson-databind-2.10.0.jar:2.10.0]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:161) ~[jackson-databind-2.10.0.jar:2.10.0]
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:130) ~[jackson-databind-2.10.0.jar:2.10.0]
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97) ~[jackson-databind-2.10.0.jar:2.10.0]
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:254) ~[jackson-databind-2.10.0.jar:2.10.0]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:288) ~[jackson-databind-2.10.0.jar:2.10.0]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245) ~[jackson-databind-2.10.0.jar:2.10.0]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27) ~[jackson-databind-2.10.0.jar:2.10.0]
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530) ~[jackson-databind-2.10.0.jar:2.10.0]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528) ~[jackson-databind-2.10.0.jar:2.10.0]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417) ~[jackson-databind-2.10.0.jar:2.10.0]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287) ~[jackson-databind-2.10.0.jar:2.10.0]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326) ~[jackson-databind-2.10.0.jar:2.10.0]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159) ~[jackson-databind-2.10.0.jar:2.10.0]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202) ~[jackson-databind-2.10.0.jar:2.10.0]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3205) ~[jackson-databind-2.10.0.jar:2.10.0]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3188) ~[jackson-databind-2.10.0.jar:2.10.0]
	at name.anton3.vkapi.methods.longpoll.AbstractLongPollEventSource.getEvents(AbstractLongPollEventSource.kt:44) ~[vk-api-methods-0.10.4.jar:?]
	at name.anton3.vkapi.methods.longpoll.AbstractLongPollEventSource$getEvents$1.invokeSuspend(AbstractLongPollEventSource.kt) ~[vk-api-methods-0.10.4.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-1.3.50.jar:1.3.50-release-112 (1.3.50)]
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241) [kotlinx-coroutines-core-1.3.2.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594) [kotlinx-coroutines-core-1.3.2.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60) [kotlinx-coroutines-core-1.3.2.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740) [kotlinx-coroutines-core-1.3.2.jar:?]
[WARN ] Network troubles
[WARN ] Network troubles
[WARN ] Network troubles
[WARN ] LongPoll error
java.net.SocketTimeoutException: timeout
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:666) ~[okhttp-4.2.2.jar:?]
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:675) ~[okhttp-4.2.2.jar:?]
	at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:142) ~[okhttp-4.2.2.jar:?]
	at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:99) ~[okhttp-4.2.2.jar:?]
	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:105) ~[okhttp-4.2.2.jar:?]
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:82) ~[okhttp-4.2.2.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112) ~[okhttp-4.2.2.jar:?]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:37) ~[okhttp-4.2.2.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112) ~[okhttp-4.2.2.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87) ~[okhttp-4.2.2.jar:?]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82) ~[okhttp-4.2.2.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112) ~[okhttp-4.2.2.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87) ~[okhttp-4.2.2.jar:?]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84) ~[okhttp-4.2.2.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112) ~[okhttp-4.2.2.jar:?]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71) ~[okhttp-4.2.2.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112) ~[okhttp-4.2.2.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87) ~[okhttp-4.2.2.jar:?]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184) ~[okhttp-4.2.2.jar:?]
	at okhttp3.RealCall$AsyncCall.run(RealCall.kt:136) ~[okhttp-4.2.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
```

**Comment by Anton3** [comment]
На настоящий момент поддерживается версия API 5.102, её надо указать в настройках группы. В ближайшее время будет поддержка версии 5.103.

**Comment by Anton3** [comment]
Добавлена поддержка 5.103. Тем не менее, в настройках группы версию всё же надо указывать.
